### ISSUE TITLE
Missing iHD driver

### ISSUE THREAD

**Issue by hazard-10** [VCDP/FFmpeg-patch#6]
Hi, there

I am stuck at installation process 3.2 Installation of Intel Media SDK
--> vainfo can't find iHD driver. 
My cpu is E5 2620 v4 @ 2.10Ghz

The problem might be that it was a server cpu and there is no iGPU (so no available driver ?). 
Is there a way to bypass that and use Cuda to for video acceleration ?

**Comment by linxie47** [comment]
Sure, you can bypass this step. But we don't support non-Intel hardware platforms right now.

**Comment by hazard-10** [comment]
Alright thanks.
