### ISSUE TITLE
No such filter : 'Detect'

### ISSUE THREAD

**Issue by hazard-10** [VCDP/FFmpeg-patch#7]
Hello again,

I switched to Ubuntu 16.04 and tried to apply the patches to ffmpeg and the patches don't seem to be applied. 

The system is clean as I just installed it over the weekend. 

Following Guidance 3.2 Build on a host machine  :
ALL the required dependencies are successfully installed through apt-get install.
I used OpenVino_p20.2.120 version. Excluded Intel-media-sdk. Did not see OpenVX in the optionally-excluded list.

libdrm, libva, & media-sdk, etc are properly installed
Clinfo & Vainfo run just fine.
Patching process runs without a hitch. 

In the final building stage, I used build-ffmpeg-dynamic and disabled librkafka as there is always an error when building its file.

At last, when I checked the installation with ffmepg -filters | grep Inference command, the output only showed ffmpeg default filters without "detect" & "classify".

Any suggestions ?

**Comment by linxie47** [comment]
Please make sure libinference_engine_c_api and libjson_c are installed correctly.

**Comment by hazard-10** [comment]
Hi Linxie, Thank you for your reply.

The build-ffmpeg script inside FFVA enables both libinference_engine_c_api and libjson_c options when running ffmpeg's configure script, and the building process has no error. Is that a sign of valid installation of these two libraries , or do I need to install them manually ?

P.S I have libjson.so under multiple directories in /usr/ and libinference_engine_c_api.so under default openvino directory.

**Comment by linxie47** [comment]
please check the ffbuild/config.log to see if there's anything wrong

**Comment by hazard-10** [comment]
output content related to classify & detect 

libdc1394_indev'
inference_classify_filter='yes'
inference_classify_filter_deps='libinference_engine_c_api libjson_c'
inference_classify_filter_select='image_inference'
inference_detect_filter='yes'
inference_detect_filter_deps='libinference_engine_c_api libjson_c'
inference_detect_filter_select='image_inference'
inference_identify_filter='yes'
inference_identify_filter_deps='libjson_c'
inference_identify_filter_select='image_inference'
inference_infer_filter='yes'
inference_infer_filter_deps='libinference_engine_c_api libjson_c'
inference_infer_filter_select='image_inference'
inference_metaconvert_filter='yes'
inference_metaconvert_filter_deps='libjson_c'
inference_metaconvert_filter_select='image_inference'
inference_python_filter='yes'
inference_python_filter_deps='python3'
inflate_filter='yes'
ingenient_demuxer='yes'
install='install'
interlace_filter='yes'

**Comment by hazard-10** [comment]
It turns out to be a missing libjson_c.so. The patch works now. Thanks for the tip !

**Comment by hazard-10** [comment]
FYI, In section 4 of getting started guide , when using FFVA on a host machine, the user has to run setup_env.sh under  FFmepg-patch/scripts/ in order to try env | grep MODELS_PATH & env | grep VIDEO_EXAMPLES_DIR, which is not mentioned in the guide.
